### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/mod-chat-login#1]
please fix

**Comment by Viste** [comment]
try #2

**Comment by disclosurez** [comment]
> 
> 
> try #2

doesnt work

**Comment by disclosurez** [comment]
fixing this https://github.com/azerothcore/azerothcore-wotlk/issues/2705 may make this module work

**Comment by Helias** [comment]
what about https://github.com/azerothcore/mod-chat-login/pull/5 ?
